AllCops:
  #RunRailsCops: true
  Exclude:
    # You could specify set of files or dirs while you want to be ignored by rubocop
    - 'vendor/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'bin/*'
    - 'Gemfile'
    - 'Gemfile.lock'
    - 'Rakefile'
    - 'Guardfile'
    - 'config.ru'
Rails:
  Enabled: true
Documentation: # Disabling documentation cop
  Enabled: false
Metrics/LineLength:
  Max: 240
Lint/UnneededDisable:
  Enabled: false
ClassLength:
  Max: 250
FrozenStringLiteralComment:
  Enabled: false
Lint/UnifiedInteger:
 Enabled: false
OutputSafety:
  Enabled: false
