# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cacac98d35a61fc52d8483453e426d1e55fb5542592ea6e01d1c67e56b0b7a1f23ce998ae81cfe75b72d39fd51db3ebd422dd400f91bc7801fb7d62b38d29c1a
  easy_pay_wallet: '50757028'
  easypay_wallet_id: '612304'
  easypay_login: '380630348377'
  easypay_password: 'zeusxlogan1715'
test:
  secret_key_base: cd00151b4ab870be62de56f47cc5068f47950efa1ece5a7b49034c619af0c78fadd55c9b52e0cdb345d507db21538f0fabd5ff239d15a9b7cffa4fb3f4141e69

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  easy_pay_wallet: <%= ENV["EASY_PAY_WALLET"] %>
  easypay_wallet_id: <%= ENV["EASY_PAY_WALLET_ID"] %>
  easypay_login: <%= ENV["EASY_PAY_LOGIN"] %>
  easypay_password: <%= ENV["EASY_PAY_PASSWORD"] %>
